name: python wheel package build

on:
  push:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2022, macos-13]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # CIBW_BEFORE_ALL_LINUX: yum install -y wget
            # wget https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz &&
            # tar xf gmp-6.3.0.tar.xz &&
            # cd gmp-6.3.0 &&
            # ./configure --enable-static -enable-cxx --enable-shared &&
            # make -j8 &&
            # make install &&
            # cd .. &&
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y gmp-devel &&
            git clone https://github.com/meelgroup/cadical.git &&
            cd cadical &&
            git checkout add_dynamic_lib &&
            CXXFLAGS=-fPIC ./configure &&
            make -j4 &&
            cd .. &&
            git clone https://github.com/meelgroup/cadiback.git &&
            cd cadiback &&
            git checkout mate &&
            ./configure &&
            make -j4 &&
            make install &&
            cd ..
          CIBW_SKIP: "*musl*"
          CIBW_ARCHS: "auto64"
          # CIBW_REPAIR_WHEEL_COMMAND: 'auditwheel repair -w {dest_dir} {wheel}'

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
      - name: Install twine
        run: python -m pip install twine
      - name: Publish wheels to PyPI 
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --skip-existing --disable-progress-bar ./wheelhouse/pycryptosat-*.whl
