root_path: &root_path runs/cifar10_res18/
epoch: &epoch 300

optimizer: &optimizer
  submodule_name: SGD
  module_name: .optim
  package_path: torch
  args:
    params:
    lr: 0.01
    momentum: 0.9 
    weight_decay: 5.0e-4

lr_scheduler: &scheduler
  submodule_name: CosineAnnealingLR
  module_name: .optim.lr_scheduler
  package_path: torch
  args:
    optimizer: 
    T_max: *epoch 

hooks: &hooks
  opt_hook:
    hook_name: OptHOOK
    hook_args:
      optimizer: 
      priority: 0
      accumulate_gradient: 1
  
  lr_scheduler_hook:
    hook_name: LrScheduleHOOK
    hook_args: 
      lr_scheduler:
      priority: 0
      mode: epoch
  
  eval_hook:
    hook_name: EvalAccHOOK
    hook_args: 
      priority: 0
  
  ddp_hook:
    hook_name: DDPHOOK
    hook_args:
      priority: 5
  
  log_hook:
    hook_name: LogHOOK
    hook_args:
      logger_name: TrainPip
      log_path: !join [*root_path, test.log]
      print_freq: 50
      only_master: True
      priority: 10
  
  ckpt_hook:
    hook_name: CkptHOOK
    hook_args:
      save_root: !join [*root_path, ckpt/]
      pretrain: 
      only_master: True
      priority: 20

engine:
  submodule_name: NNEngine
  args:
    data: !cross_ref [cfg/dataset/cifar10.yaml]
    model: !cross_ref [cfg/model/resnet18.yaml]
    criterion: !cross_ref [cfg/criterion/cross_entropy.yaml]
    optimizer: *optimizer
    lr_scheduler: *scheduler
    hooks: *hooks
    amp: False

